language: java
script: gradle uploadArchives
branches:
  only:
    - master
env:
  global:
  - secure: g7hUitbLT4i6ZFU/p/YSGGcL9ah91asHiV19KAN5fxERKfKO8BnO0xw80w38x8V1gJERn9GRKYq5G/bMo0PhB38+/RBxivJmX+i/+sHV9v5ichScfTDrrGsM1bScHxL8MhJh6Hc3McWz2etlpecmEAXFNSg0CnoBpdWpa3SKUm0=
  - secure: ddcOk6wmDz/gTJIXd7kOFJ3HH9QY+/Q8J5SyucI0OqSladKyTJQxfMgq9P9VSxncPGldi4IuyPhjnD94ddq1jgoXwscBzOwBzHndDofmaUnHlsRgcOzWS3FCbvnTRVjW8OSXOj8CdxB3FzjMUMOtOID0z7TYBnLq2uEsB4ebRbI=
